/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Mor } from "./Mor";
import { MorCountArgs } from "./MorCountArgs";
import { MorFindManyArgs } from "./MorFindManyArgs";
import { MorFindUniqueArgs } from "./MorFindUniqueArgs";
import { DeleteMorArgs } from "./DeleteMorArgs";
import { MorService } from "../mor.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Mor)
export class MorResolverBase {
  constructor(
    protected readonly service: MorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Mor",
    action: "read",
    possession: "any",
  })
  async _morsMeta(
    @graphql.Args() args: MorCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Mor])
  @nestAccessControl.UseRoles({
    resource: "Mor",
    action: "read",
    possession: "any",
  })
  async mors(@graphql.Args() args: MorFindManyArgs): Promise<Mor[]> {
    return this.service.mors(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Mor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Mor",
    action: "read",
    possession: "own",
  })
  async mor(@graphql.Args() args: MorFindUniqueArgs): Promise<Mor | null> {
    const result = await this.service.mor(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Mor)
  @nestAccessControl.UseRoles({
    resource: "Mor",
    action: "delete",
    possession: "any",
  })
  async deleteMor(@graphql.Args() args: DeleteMorArgs): Promise<Mor | null> {
    try {
      return await this.service.deleteMor(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
